/**
 * Generates ACCESS.md from the capability registry.
 *
 * The registry is what the route guards enforce, so a table built from it cannot
 * describe permissions the server does not have. What *can* drift is the
 * committed file lagging the registry, which `--check` exists to catch.
 *
 *   node src/scripts/generateAccessDoc.js          # write ACCESS.md
 *   node src/scripts/generateAccessDoc.js --check  # fail if it is stale
 *   node src/scripts/generateAccessDoc.js --users  # also list who holds each role
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { CAPABILITIES } from '../lib/capabilities.js';
import { ROLE_HIERARCHY } from '../middleware/auth.js';
import { GLOBAL_SCOPE_ROLES } from '../lib/scope.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DOC_PATH = join(__dirname, '../../../ACCESS.md');

/** Highest first, so the table reads left-to-right from most access to least. */
const ROLES = Object.entries(ROLE_HIERARCHY)
  .sort((a, b) => b[1] - a[1])
  .map(([role]) => role);

const LABELS = {
  SUPER_ADMIN: 'Super Admin',
  ADMIN: 'Admin',
  HR: 'HR',
  MASTER_OF_HOUSE: 'Master of House',
  HEAD_CHEF: 'Head Chef',
  STAFF: 'Staff',
};

const allows = (role, minRole) => ROLE_HIERARCHY[role] >= ROLE_HIERARCHY[minRole];

export function buildDoc() {
  const groups = new Map();
  for (const [key, cap] of Object.entries(CAPABILITIES)) {
    if (!groups.has(cap.group)) groups.set(cap.group, []);
    groups.get(cap.group).push({ key, ...cap });
  }

  const header = `| Action | ${ROLES.map((r) => LABELS[r]).join(' | ')} |`;
  const rule = `|---|${ROLES.map(() => '---').join('|')}|`;

  const sections = [...groups].map(([group, caps]) => {
    const rows = caps.map((c) => {
      const cells = ROLES.map((r) => (allows(r, c.minRole) ? '✅' : '—'));
      return `| ${c.label} | ${cells.join(' | ')} |`;
    });
    // Separate blockquotes, not consecutive lines — adjacent `>` lines merge
    // into one paragraph and the notes run together.
    const notes = caps
      .filter((c) => c.note)
      .flatMap((c) => [`> **${c.label}** — ${c.note}`, '']);
    return [`### ${group}`, '', header, rule, ...rows, ...(notes.length ? [''] : []), ...notes]
      .join('\n')
      .trimEnd();
  });

  const scoped = ROLES.filter((r) => !GLOBAL_SCOPE_ROLES.includes(r));

  // Read off the registry, not written by hand. The first draft of this section
  // claimed "only an Admin or above can enrol someone" while the table two
  // paragraphs up correctly showed HR — the exact drift this file exists to stop,
  // reproduced inside it.
  const floor = (key) => LABELS[CAPABILITIES[key].minRole];

  return `# Who can do what

<!-- Generated by \`npm run access:doc\`. Do not edit by hand — edit
     server/src/lib/capabilities.js, which is what the route guards enforce,
     and regenerate. \`npm run access:check\` fails if this file is stale. -->

Every role inherits everything the roles below it can do: they are ranked, and
each action names the lowest rank that may perform it. Most access first:

${ROLES.map((r) => `- **${LABELS[r]}** (${ROLE_HIERARCHY[r]})`).join('\n')}

## Reading

Anyone signed in can read, but not the same amount.

| | Sees |
|---|---|
| ${GLOBAL_SCOPE_ROLES.map((r) => LABELS[r]).join(', ')} | Every restaurant |
| ${scoped.map((r) => LABELS[r]).join(', ')} | Only their own restaurant |

That narrowing is applied server-side from the signed-in account, not from a
query parameter, so it cannot be widened by asking differently.

## Writing

${sections.join('\n\n')}

## How accounts are issued

- Enrolling someone needs **${floor('EMPLOYEE_CREATE')}** or above. Issuing a
  replacement password or deactivating an account needs
  **${floor('EMPLOYEE_RESET_PW')}** or above — taking over an existing account is
  a bigger step than creating a new one.
- A new account receives a one-time password, shown once, and can reach nothing
  until it sets its own — the restriction travels in the signed token, so it
  cannot be skipped by avoiding the screen.
- **Super Admin**, **Admin** and **HR** belong to no restaurant. The other three
  are pinned to one and see only that.
`;
}

const doc = buildDoc();

if (process.argv.includes('--check')) {
  const current = existsSync(DOC_PATH) ? readFileSync(DOC_PATH, 'utf8') : '';
  if (current !== doc) {
    console.error(
      '\nACCESS.md is out of date with server/src/lib/capabilities.js.\n' +
      'Run `npm run access:doc` and commit the result.\n'
    );
    process.exit(1);
  }
  console.log('ACCESS.md is up to date.');
} else {
  writeFileSync(DOC_PATH, doc);
  console.log(`Wrote ACCESS.md — ${Object.keys(CAPABILITIES).length} capabilities across ${ROLES.length} roles.`);
}

// Who currently holds each role. Printed rather than written into the file:
// the document is committed, and employee names and addresses are not for a
// repository.
if (process.argv.includes('--users')) {
  const { PrismaClient } = await import('@prisma/client');
  const prisma = new PrismaClient();
  const people = await prisma.employee.findMany({
    where: { isActive: true },
    select: { name: true, email: true, role: true, outlet: { select: { name: true } } },
    orderBy: { name: 'asc' },
  });
  console.log('\nWho holds each role right now:\n');
  for (const role of ROLES) {
    const holders = people.filter((p) => p.role === role);
    console.log(`  ${LABELS[role].padEnd(16)} ${holders.length === 0 ? '—' : holders
      .map((p) => `${p.name} <${p.email}>${p.outlet ? ` · ${p.outlet.name}` : ''}`)
      .join('\n' + ' '.repeat(19))}`);
  }
  console.log();
  await prisma.$disconnect();
}
